export const meals = [
  {
    id: 'golden-bone-broth',
    name: 'Golden Bone Broth',
    description: 'Rich, nourishing bone broth with turmeric and ginger',
    price: 18,
    category: 'Broth',
    image: '/images/golden-broth.jpg',
    tags: ['gluten-free', 'dairy-free'],
    calories: 80,
    protein: 8,
    carbs: 2,
    type: 'broth'
  },
  {
    id: 'warming-chicken-soup',
    name: 'Warming Chicken Soup',
    description: 'Comforting chicken soup with healing herbs and vegetables',
    price: 22,
    category: 'Soup',
    image: '/images/chicken-soup.jpg',
    tags: ['gluten-free', 'dairy-free'],
    calories: 220,
    protein: 24,
    carbs: 18,
    type: 'soup'
  },
  {
    id: 'lentil-dal',
    name: 'Nourishing Lentil Dal',
    description: 'Spiced red lentil dal with warming postpartum spices',
    price: 20,
    category: 'Full-Meal',
    image: '/images/lentil-dal.jpg',
    tags: ['vegan', 'gluten-free'],
    calories: 320,
    protein: 18,
    carbs: 45,
    type: 'full-meal'
  },
  {
    id: 'healing-veggie-broth',
    name: 'Healing Vegetable Broth',
    description: 'Light, mineral-rich vegetable broth with sea vegetables',
    price: 16,
    category: 'Broth',
    image: '/images/veggie-broth.jpg',
    tags: ['vegan', 'gluten-free'],
    calories: 45,
    protein: 2,
    carbs: 8,
    type: 'broth'
  },
  {
    id: 'traditional-congee',
    name: 'Traditional Congee',
    description: 'Healing rice porridge with ginger and scallions',
    price: 18,
    category: 'Full-Meal',
    image: '/images/congee.jpg',
    tags: ['gluten-free', 'traditional', 'easy-digest'],
    calories: 180,
    protein: 8,
    carbs: 35,
    type: 'full-meal'
  },
  {
    id: 'miso-mushroom',
    name: 'Miso Mushroom Soup',
    description: 'Umami-rich miso soup with shiitake mushrooms',
    price: 19,
    category: 'Soup',
    image: '/images/miso-soup.jpg',
    tags: ['probiotic', 'mineral-rich'],
    calories: 95,
    protein: 8,
    carbs: 12,
    type: 'soup'
  },
  {
    id: 'salmon-quinoa-bowl',
    name: 'Salmon Quinoa Bowl',
    description: 'Omega-rich salmon with quinoa and roasted vegetables',
    price: 24,
    category: 'Full-Meal',
    image: '/images/salmon-bowl.jpg',
    tags: ['gluten-free', 'high-protein'],
    calories: 450,
    protein: 35,
    carbs: 42,
    type: 'full-meal'
  },
  {
    id: 'pho-beef',
    name: 'Postpartum Pho',
    description: 'Traditional Vietnamese pho with healing spices',
    price: 23,
    category: 'Soup',
    image: '/images/pho.jpg',
    tags: ['traditional', 'gluten-free'],
    calories: 380,
    protein: 28,
    carbs: 48,
    type: 'soup'
  },
  {
    id: 'sweet-potato-curry',
    name: 'Sweet Potato Curry',
    description: 'Nourishing curry with sweet potato and chickpeas',
    price: 21,
    category: 'Full-Meal',
    image: '/images/curry.jpg',
    tags: ['vegan', 'gluten-free'],
    calories: 340,
    protein: 12,
    carbs: 52,
    type: 'full-meal'
  },
  {
    id: 'chicken-zucchini-soup',
    name: 'Chicken Zucchini Soup',
    description: 'Light chicken soup with zucchini noodles',
    price: 20,
    category: 'Soup',
    image: '/images/zucchini-soup.jpg',
    tags: ['gluten-free', 'dairy-free', 'low-carb'],
    calories: 180,
    protein: 22,
    carbs: 12,
    type: 'soup'
  },
  {
    id: 'turkey-vegetable-stew',
    name: 'Turkey Vegetable Stew',
    description: 'Hearty stew with ground turkey and root vegetables',
    price: 23,
    category: 'Full-Meal',
    image: '/images/turkey-stew.jpg',
    tags: ['gluten-free', 'dairy-free'],
    calories: 320,
    protein: 26,
    carbs: 28,
    type: 'full-meal'
  },
  {
    id: 'ginger-turmeric-broth',
    name: 'Ginger Turmeric Broth',
    description: 'Anti-inflammatory broth with fresh ginger and turmeric',
    price: 17,
    category: 'Broth',
    image: '/images/turmeric-broth.jpg',
    tags: ['vegan', 'anti-inflammatory'],
    calories: 35,
    protein: 1,
    carbs: 6,
    type: 'broth'
  },
];

export const packages = [
  {
    id: 'starter-recovery',
    name: 'Starter Recovery Plan',
    description: 'Perfect introduction to postpartum nourishment for new mothers',
    duration: 5,
    mealCount: 5,
    price: 85,
    regularPrice: 95,
    savings: 10,
    pricePerMeal: 17,
    image: '/images/starter-package.jpg',
    features: [
      'Gentle on digestion',
      'Traditional healing foods',
      'Anti-inflammatory ingredients'
    ],
    category: 'gentle'
  },
  {
    id: 'full-healing-journey',
    name: 'Full Healing Journey',
    description: 'Complete 14-day postpartum recovery program with diverse nourishing meals',
    duration: 14,
    mealCount: 12,
    price: 245,
    regularPrice: 280,
    savings: 35,
    pricePerMeal: 20.42,
    image: '/images/full-package.jpg',
    features: [
      'Complete nutrition support',
      'Lactation-friendly',
      'Hormone balancing'
    ],
    category: 'popular',
    badge: 'Most Popular'
  },
  {
    id: 'lactation-support',
    name: 'Nourish & Lactation Support',
    description: 'Specialized meals to support healthy breastfeeding and milk production',
    duration: 7,
    mealCount: 7,
    price: 165,
    regularPrice: 185,
    savings: 20,
    pricePerMeal: 23.57,
    image: '/images/lactation-package.jpg',
    features: [
      'Lactation support',
      'Healthy fats for milk quality',
      'High protein content'
    ],
    category: 'lactation'
  },
];
